import { LanguageProvider } from '@inlang/paraglide-next';

import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from '@/components/ui/sonner';
import './globals.css';
import Providers from '@/components/layout/providers';
import { auth } from '@/auth';

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const locale = 'en';
  return (
    <LanguageProvider>
      <html lang={locale}>
        <body
          className={`${lato.className} antialiased`}
          suppressHydrationWarning
        >
          <NextTopLoader showSpinner={false} />
          <NuqsAdapter>
            <Providers session={session}>
              <Toaster />
              {children}
            </Providers>
          </NuqsAdapter>
        </body>
      </html>
    </LanguageProvider>
  );
}
